Collecting django-allauth
  Using cached django_allauth-65.2.0-py3-none-any.whl
Requirement already satisfied: Django>=4.2.16 in c:\users\fatim\tired\django-ecommerce\env\lib\site-packages (from django-allauth) (5.1.3)
Requirement already satisfied: asgiref>=3.8.1 in c:\users\fatim\tired\django-ecommerce\env\lib\site-packages (from django-allauth) (3.8.1)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\fatim\tired\django-ecommerce\env\lib\site-packages (from Django>=4.2.16->django-allauth) (0.5.2)
Requirement already satisfied: tzdata in c:\users\fatim\tired\django-ecommerce\env\lib\site-packages (from Django>=4.2.16->django-allauth) (2024.2)
Installing collected packages: django-allauth
Successfully installed django-allauth-65.2.0
